### ISSUE TITLE
registerPackages - pojedyncza przesyłka

### ISSUE THREAD

**Issue by mgralikowski** [t3ko/inpost-api-php-sdk#1]
Czy w linii 212 pliku Client zamiast false nie powinno być np. return [ ] ?

Nie wiem czy dobrze korzystam z klasy i wzorca builder.

```
$api = new Client(config('inpost.login'), config('inpost.password'), config('inpost.testMode') ? Client::SANDBOX_API_ENDPOINT : Client::PRODUCTION_API_ENDPOINT);

$package = new SelfSentPackageBuilder('sender@gmail.com', 'A', 'client@gmail.com', '50000000', 'KAT213', '');
$shipments = [$package->build()];
$api->registerShipments($shipments);
```
Bo przy powyższym otrzymuje błąd:
> array_merge(): Argument #1 is not an array

wynikający z braku elementów registeredPackages i przy łączeniu tablic wyskakuje błąd. Gdyby zmienić false na pustą tablicę to już wszystko działa. Bez tego sama przesyłka się też dodaje ale wypluwa błąd. Będę wdzięczny za pomoc.

**Comment by t3ko** [comment]
Dzięki za zgłoszenie. Rzeczywiście, w przypadku gdy rejestrowany jest tylko jeden typ przesyłki naraz - a to pewnie 99,99% case-ów - zawsze któryś z parametrów do `array_merge` nie jest tablicą co jest błędem. Zaraz wprowadzę poprawkę.

**Comment by mgralikowski** [comment]
Dzięki za poprawkę no i upewnienie mnie, że to nie mój błąd ;)

Ostatecznie zrobiłem fork'a z poprawką i dodatkowymi metodami, których mi brakowało.
